### ISSUE TITLE
Example Code

### ISSUE THREAD

**Issue by aceat64** [in2-arduino/Wiegand#1]
This looks like one of the best written Wiegand libraries for Arduino. Would you mind providing some example code? Specifically for how use this with multiple readers.

Thank you.

**Comment by in2-arduino** [comment]
Hi,

I'm glad you like it :)

You can find example code in our door controller project
https://github.com/in2-arduino/Automatska_vrata. Unfortunately, some
comments are not in english, but they are not essential and you should be
able to follow the code.

Since we only have a single reader, we've never actually tested multiple
readers scenario, but it should work. You'll need a Mega or Leonardo board
since Uno only has two interrupt pins and you need two for each Wiegand
bus. Otherwise you'll have to change the library to use regular pins or pin
change interrupt.

In your sketch, you would simply instantiate multiple Wiegand objects, for
instance on Mega:

Wiegand wiegand1(2, 3); // uses interrupts 0 and 1 (physical pins 2 and 3)
Wiegand wiegand2(21, 20); // uses interrupts 2 and 3 (physical pins 21 and
20)
...

Later in your control loop you check both objects one at a time and build
from that.

Hope it helps :)

Oh, I'm not really at home with Wiegand equipment, but I'd expect that
there's a way to connect multiple readers on the SAME bus and use some
addressing scheme to differentiate between them. If I were you, I'd
probably explore that first. Using two pins per reader is hardly practical
in any real application where you have tens or hundreds of readers.

Kind regards

2015-02-15 7:06 GMT+01:00 Andrew LeCody notifications@github.com:
